version: '4.27.2'
services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - ./dbInit.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
    expose: 
      - 3306
    environment:
      MYSQL_DATABASE: money_app
      MYSQL_ROOT_PASSWORD: stoopidhead
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pstoopidhead"]
      interval: 1s
      retries: 12

  node_api:
    container_name: node_api
    image: money_app_api
    build: ./server
    ports: 
      - "3001:3001"
    environment:
      WAIT_HOSTS: mysql_db:3306
      EXTERNAL_PORT: 3001
      MYSQLUSER: root
      MYSQLPASSWORD: stoopidhead
      MYSQLDB: money_app
      MYSQLHOST: mysql_db
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - internalnet

  react_app:
    container_name: react_app
    image: money_app_react
    build: ./react-app
    ports: 
      - "3000:3000"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
